"""
Export the trained autoencoder as plain JSON weights.

Deliberately NOT ONNX. The model is ~6k parameters — an MLP with four Linear
layers and ReLU. Hand-rolled inference for that is about 25 lines of
dependency-free JavaScript, whereas ONNX Runtime Web costs a ~2 MB WASM
download in a PWA whose entire selling point is working offline on a bad
connection.

The same JSON also ports directly to a C array for the ESP32 later, which an
ONNX graph would not.

Writes:
  ../backend/src/ml/model.json   (weights + normalisation + threshold)

Usage:
    python export_weights.py
"""

import json
from pathlib import Path

import numpy as np
import torch

from train import AutoEncoder

HERE = Path(__file__).parent
ART = HERE / "artifacts"
OUT = HERE.parent / "backend" / "src" / "ml" / "model.json"


def main():
    ckpt_path = ART / "autoencoder.pt"
    report_path = ART / "report.json"
    if not ckpt_path.exists():
        raise SystemExit(f"missing {ckpt_path} — run train.py first")

    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    report = json.loads(report_path.read_text())

    model = AutoEncoder(ckpt["n_in"], ckpt["hidden"], ckpt["latent"])
    model.load_state_dict(ckpt["state_dict"])
    model.eval()

    # Collect the four Linear layers in forward order.
    layers = []
    for module in list(model.encoder) + list(model.decoder):
        if isinstance(module, torch.nn.Linear):
            W = module.weight.detach().numpy()   # (out, in)
            b = module.bias.detach().numpy()     # (out,)
            layers.append(
                {
                    "in": int(W.shape[1]),
                    "out": int(W.shape[0]),
                    # Row-major, one flat list per layer — the JS reads it as
                    # out-by-in, matching torch's layout exactly.
                    "W": [round(float(v), 6) for v in W.reshape(-1)],
                    "b": [round(float(v), 6) for v in b],
                }
            )

    # ReLU after every layer except the final (linear) output.
    activations = ["relu"] * (len(layers) - 1) + ["none"]

    payload = {
        "_comment": "Autoencoder for vitals anomaly detection. Generated by ml/export_weights.py — do not hand-edit.",
        "dataset": "BIDMC PPG and Respiration Dataset v1.0.0 (PhysioNet)",
        "features": report["features"],
        "window": report["window_seconds"],
        "normalisation": {"mean": report["norm_mean"], "std": report["norm_std"]},
        "threshold": report["threshold"],
        "metrics": report["test"],
        "layers": layers,
        "activations": activations,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload))

    n_w = sum(len(l["W"]) + len(l["b"]) for l in layers)
    size_kb = OUT.stat().st_size / 1024
    print(f"exported {n_w:,} parameters -> {OUT}  ({size_kb:.1f} KB)")

    # --- verify the export round-trips ---
    rng = np.random.default_rng(0)
    x = rng.standard_normal((5, ckpt["n_in"])).astype(np.float32)

    with torch.no_grad():
        torch_out = model(torch.from_numpy(x)).numpy()

    h = x
    for layer, act in zip(layers, activations):
        W = np.asarray(layer["W"], dtype=np.float32).reshape(layer["out"], layer["in"])
        b = np.asarray(layer["b"], dtype=np.float32)
        h = h @ W.T + b
        if act == "relu":
            h = np.maximum(h, 0.0)

    max_diff = float(np.abs(h - torch_out).max())
    print(f"round-trip check: max abs difference {max_diff:.2e}")
    if max_diff > 1e-4:
        raise SystemExit("EXPORT MISMATCH — the JSON does not reproduce the torch model")
    print("export verified.")


if __name__ == "__main__":
    main()
